#' Results from a MetaNetAssoc analysis
#'
#' @slot call The matched analysis call.
#' @slot parameters Analysis settings.
#' @slot scores Metabolite-term score table.
#' @slot edges Auditable metabolite-gene-gene-term paths.
#' @slot term_table Terms retained for analysis.
#' @slot qc Quality-control summary.
#' @slot unmatched Unmatched metabolites and genes.
#' @slot term_reduction Mapping generated by optional term reduction.
#' @exportClass MetaNetResult
setClass(
  "MetaNetResult",
  slots = c(
    call = "ANY",
    parameters = "list",
    scores = "data.frame",
    edges = "data.frame",
    term_table = "data.frame",
    qc = "data.frame",
    unmatched = "list",
    term_reduction = "data.frame"
  )
)

setMethod("show", "MetaNetResult", function(object) {
  cat("MetaNetAssoc result\n")
  cat("  metabolite-term pairs:", nrow(object@scores), "\n")
  cat("  supported paths:", nrow(object@edges), "\n")
  cat("  retained terms:", nrow(object@term_table), "\n")
  if (length(object@unmatched$metabolites)) {
    cat("  unmatched metabolites:", length(object@unmatched$metabolites), "\n")
  }
  invisible(object)
})

